-- Esquema inicial del catalogo (antes lo generaba Hibernate con ddl-auto: update)
CREATE TABLE auto (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destino_iata           VARCHAR(3)     NOT NULL,
    categoria              VARCHAR(20)    NOT NULL,
    marca                  VARCHAR(60)    NOT NULL,
    modelo                 VARCHAR(60)    NOT NULL,
    plazas                 INTEGER        NOT NULL,
    transmision_automatica BOOLEAN        NOT NULL,
    precio_base_dia        NUMERIC(12, 2) NOT NULL,
    moneda                 VARCHAR(3)     NOT NULL,
    activo                 BOOLEAN        NOT NULL DEFAULT TRUE,
    en_revision            BOOLEAN        NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_auto_destino ON auto (destino_iata);

CREATE TABLE bloqueo_auto (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auto_id     BIGINT      NOT NULL REFERENCES auto (id),
    desde       DATE        NOT NULL,
    hasta       DATE        NOT NULL,
    reserva_ref VARCHAR(40) NOT NULL
);
CREATE INDEX ix_bloqueo_reserva ON bloqueo_auto (reserva_ref);
CREATE INDEX ix_bloqueo_auto_fechas ON bloqueo_auto (auto_id, desde, hasta);

CREATE TABLE historial_precio (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_producto  VARCHAR(20)              NOT NULL,
    producto_ref   VARCHAR(1000)            NOT NULL,
    destino_iata   VARCHAR(3),
    precio         NUMERIC(12, 2)           NOT NULL,
    moneda         VARCHAR(3)               NOT NULL,
    fecha_registro TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_historial_fecha ON historial_precio (fecha_registro);
