CREATE TABLE pago (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id    BIGINT                   NOT NULL UNIQUE,   -- idempotencia: un pago por reserva
    monto         NUMERIC(12, 2)           NOT NULL,
    moneda        VARCHAR(3)               NOT NULL,
    proveedor     VARCHAR(30)              NOT NULL,
    ref_proveedor VARCHAR(60),
    estado        VARCHAR(20)              NOT NULL,
    motivo        VARCHAR(200),
    fecha         TIMESTAMP WITH TIME ZONE NOT NULL
);
