server:
  port: ${PORT:8085}

spring:
  application:
    name: notificaciones-service
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2s
          multiplier: 2
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}

travelhub:
  mail:
    remitente: reservas@travelhub.local
  servicios:
    ia: ${IA_URL:http://localhost:8000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    mail:
      enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%X{correlationId:-sin-id}] %logger{36} - %msg%n"
