-- Esquema inicial de reservas (antes lo generaba Hibernate con ddl-auto: update)
CREATE TABLE viajero (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(80)  NOT NULL,
    apellido         VARCHAR(80)  NOT NULL,
    email            VARCHAR(120) NOT NULL UNIQUE,
    documento        VARCHAR(20)  NOT NULL,
    fecha_nacimiento DATE         NOT NULL,
    preferencias     VARCHAR(200)
);

CREATE TABLE reserva (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viajero_id BIGINT                   NOT NULL REFERENCES viajero (id),
    destino    VARCHAR(3)               NOT NULL,
    desde      DATE                     NOT NULL,
    hasta      DATE                     NOT NULL,
    pasajeros  INTEGER                  NOT NULL,
    estado     VARCHAR(20)              NOT NULL,
    total      NUMERIC(12, 2),
    moneda     VARCHAR(3),
    motivo     VARCHAR(300),
    creada_en  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_reserva_viajero ON reserva (viajero_id);
CREATE INDEX ix_reserva_estado ON reserva (estado, creada_en);

CREATE TABLE item_reserva (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id      BIGINT         NOT NULL REFERENCES reserva (id) ON DELETE CASCADE,
    tipo            VARCHAR(20)    NOT NULL,
    producto_id     VARCHAR(1000)  NOT NULL,
    descripcion     VARCHAR(200)   NOT NULL,
    precio_base     NUMERIC(12, 2) NOT NULL,
    precio_cotizado NUMERIC(12, 2),
    ref_externa     VARCHAR(80),
    estado          VARCHAR(20)    NOT NULL
);
CREATE INDEX ix_item_reserva ON item_reserva (reserva_id);

CREATE TABLE saga_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id BIGINT                   NOT NULL,
    paso       VARCHAR(40)              NOT NULL,
    estado     VARCHAR(20)              NOT NULL,
    detalle    VARCHAR(500),
    fecha      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_saga_reserva ON saga_log (reserva_id);

CREATE TABLE seguimiento_destino (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viajero_id      BIGINT         NOT NULL REFERENCES viajero (id),
    destino         VARCHAR(3)     NOT NULL,
    tipo_producto   VARCHAR(20)    NOT NULL,
    precio_objetivo NUMERIC(12, 2) NOT NULL,
    moneda          VARCHAR(3)     NOT NULL,
    activo          BOOLEAN        NOT NULL DEFAULT TRUE
);
