-- Idempotencia: el mismo Idempotency-Key devuelve la reserva ya creada (doble clic, reintentos)
ALTER TABLE reserva ADD COLUMN idempotency_key VARCHAR(80);
CREATE UNIQUE INDEX ux_reserva_idempotency ON reserva (idempotency_key);

-- Transactional Outbox: el evento se guarda en la MISMA transaccion que el cambio de estado
-- y un relay lo publica en RabbitMQ. Si RabbitMQ esta caido, el evento no se pierde.
CREATE TABLE outbox_evento (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routing_key    VARCHAR(80)              NOT NULL,
    tipo           VARCHAR(200)             NOT NULL,
    payload        TEXT                     NOT NULL,
    correlation_id VARCHAR(80),
    creado_en      TIMESTAMP WITH TIME ZONE NOT NULL,
    publicado_en   TIMESTAMP WITH TIME ZONE,
    intentos       INTEGER                  NOT NULL DEFAULT 0
);
CREATE INDEX ix_outbox_pendientes ON outbox_evento (id) WHERE publicado_en IS NULL;
