-- Viaje compartido: cada reserva tiene 1..N participantes que pagan su parte antes de vence_en.
ALTER TABLE reserva ADD COLUMN compartida BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE reserva ADD COLUMN vence_en TIMESTAMP WITH TIME ZONE;
ALTER TABLE reserva ADD COLUMN credito_aplicado NUMERIC(12, 2) NOT NULL DEFAULT 0;
UPDATE reserva SET vence_en = creada_en + INTERVAL '15 minutes' WHERE vence_en IS NULL;
ALTER TABLE reserva ALTER COLUMN vence_en SET NOT NULL;
CREATE INDEX ix_reserva_vence ON reserva (estado, vence_en);

-- Proteccion de precio: ultimo precio ya compensado para cada item
ALTER TABLE item_reserva ADD COLUMN precio_protegido NUMERIC(12, 2);

CREATE TABLE participante (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id     BIGINT                   NOT NULL REFERENCES reserva (id) ON DELETE CASCADE,
    nombre         VARCHAR(120),
    email          VARCHAR(120)             NOT NULL,
    token          VARCHAR(40)              NOT NULL UNIQUE,
    monto          NUMERIC(12, 2)           NOT NULL,
    estado         VARCHAR(20)              NOT NULL,
    organizador    BOOLEAN                  NOT NULL DEFAULT FALSE,
    pago_ref       VARCHAR(60),
    motivo         VARCHAR(200),
    actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_participante_reserva ON participante (reserva_id);

-- Credito del viajero: OTORGADO (+), USO (-), DEVOLUCION (+)
CREATE TABLE movimiento_credito (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viajero_id BIGINT                   NOT NULL REFERENCES viajero (id),
    reserva_id BIGINT,
    item_id    BIGINT,
    monto      NUMERIC(12, 2)           NOT NULL,
    moneda     VARCHAR(3)               NOT NULL,
    tipo       VARCHAR(20)              NOT NULL,
    motivo     VARCHAR(300),
    fecha      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_credito_viajero ON movimiento_credito (viajero_id);
